// frontend/src/components/Breadcrumbs.vue
<script setup lang="ts">
import { RouterLink, type RouteLocationRaw } from "vue-router";

export interface Crumb {
  label: string;
  to?: RouteLocationRaw;
}

defineProps<{ items: Crumb[] }>();
</script>

<template>
  <nav class="breadcrumbs" aria-label="Breadcrumb">
    <ol>
      <li><RouterLink to="/">Dashboard</RouterLink></li>
      <li v-for="(c, i) in items" :key="i">
        <RouterLink v-if="c.to && i < items.length - 1" :to="c.to">{{ c.label }}</RouterLink>
        <span v-else :aria-current="i === items.length - 1 ? 'page' : undefined">{{ c.label }}</span>
      </li>
    </ol>
  </nav>
</template>

// frontend/src/components/Breadcrumbs.tsx
import { Link } from "react-router-dom";

export interface Crumb {
  label: string;
  to?: string;
  state?: unknown;
}

export function Breadcrumbs({ items }: { items: Crumb[] }) {
  return (
    <nav className="breadcrumbs" aria-label="Breadcrumb">
      <ol>
        <li>
          <Link to="/">Dashboard</Link>
        </li>
        {items.map((c, i) => (
          <li key={i}>
            {c.to && i < items.length - 1 ? (
              <Link to={c.to} state={c.state}>
                {c.label}
              </Link>
            ) : (
              <span aria-current={i === items.length - 1 ? "page" : undefined}>{c.label}</span>
            )}
          </li>
        ))}
      </ol>
    </nav>
  );
}
