// frontend/src/components/CiLink.vue
<script setup lang="ts">
import { computed } from "vue";
import { RouterLink } from "vue-router";
import { extendTrail, type TrailStep } from "../lib/trail";

/** Link to a CI detail page. Pass `from` + `trail` to carry the walk trail into the breadcrumb. */
const props = withDefaults(defineProps<{ id: string; from?: TrailStep; trail?: TrailStep[] }>(), { from: undefined, trail: () => [] });
const to = computed(() => ({
  path: `/cis/${props.id}`,
  state: props.from ? { trail: extendTrail(props.trail, props.from, props.id) } : undefined,
}));
</script>

<template>
  <RouterLink :to="to"><slot /></RouterLink>
</template>

// frontend/src/components/CiLink.tsx
import { Link } from "react-router-dom";
import { extendTrail, type TrailStep } from "../lib/trail";

/** Link to a CI detail page. Pass `from` + `trail` to carry the walk trail into the breadcrumb. */
export function CiLink({
  id,
  children,
  from,
  trail = [],
}: {
  id: string;
  children: React.ReactNode;
  from?: TrailStep;
  trail?: TrailStep[];
}) {
  return (
    <Link to={`/cis/${id}`} state={from ? { trail: extendTrail(trail, from, id) } : undefined}>
      {children}
    </Link>
  );
}
