// frontend/src/components/CiPicker.tsx
import { useId, useState } from "react";
import { useCiList, type CiSummary } from "../api/queries";
import { useDebounced } from "../lib/hooks";

/**
 * Type-ahead picker for a configuration item. Queries the API server-side
 * (optionally restricted to a class and its subclasses); never loads the inventory.
 */
export function CiPicker({
  id,
  classId,
  excludeId,
  selected,
  onSelect,
  placeholder = "Search by name, hostname, IP…",
  invalid,
  describedBy,
}: {
  id?: string;
  classId?: string | null;
  excludeId?: string;
  selected: { id: string; name: string } | null;
  onSelect: (ci: CiSummary | null) => void;
  placeholder?: string;
  invalid?: boolean;
  describedBy?: string;
}) {
  const autoId = useId();
  const inputId = id ?? autoId;
  const listId = `${inputId}-list`;
  const [text, setText] = useState("");
  const [open, setOpen] = useState(false);
  const [active, setActive] = useState(0);
  const q = useDebounced(text.trim(), 200);
  const { data, isFetching, isError } = useCiList({
    q: q || undefined,
    classId: classId || undefined,
    limit: 15,
    sort: "name",
  });
  const items = (data?.data ?? []).filter((c) => c.id !== excludeId);

  if (selected) {
    return (
      <div className="checkbox-row">
        <strong>{selected.name}</strong>
        <button type="button" className="btn btn-sm" onClick={() => onSelect(null)} aria-label={`Clear ${selected.name}`}>
          Change
        </button>
      </div>
    );
  }

  const choose = (ci: CiSummary) => {
    onSelect(ci);
    setText("");
    setOpen(false);
  };

  return (
    <div className="combo">
      <input
        id={inputId}
        type="search"
        role="combobox"
        aria-expanded={open}
        aria-controls={listId}
        aria-autocomplete="list"
        aria-activedescendant={open && items[active] ? `${listId}-${active}` : undefined}
        aria-invalid={invalid || undefined}
        aria-describedby={describedBy}
        autoComplete="off"
        placeholder={placeholder}
        value={text}
        onChange={(e) => {
          setText(e.target.value);
          setOpen(true);
          setActive(0);
        }}
        onFocus={() => setOpen(true)}
        onBlur={() => setTimeout(() => setOpen(false), 150)}
        onKeyDown={(e) => {
          if (e.key === "ArrowDown") {
            e.preventDefault();
            setOpen(true);
            setActive((a) => Math.min(a + 1, items.length - 1));
          } else if (e.key === "ArrowUp") {
            e.preventDefault();
            setActive((a) => Math.max(a - 1, 0));
          } else if (e.key === "Enter" && open && items[active]) {
            e.preventDefault();
            choose(items[active]);
          } else if (e.key === "Escape") {
            setOpen(false);
          }
        }}
        style={{ width: 280 }}
      />
      {open && (
        <ul className="combo-list" id={listId} role="listbox">
          {isError && <li className="note">Search failed</li>}
          {!isError && items.length === 0 && <li className="note">{isFetching ? "Searching…" : "No matching CIs"}</li>}
          {items.map((ci, i) => (
            <li
              key={ci.id}
              id={`${listId}-${i}`}
              role="option"
              aria-selected={i === active}
              onMouseDown={(e) => {
                e.preventDefault();
                choose(ci);
              }}
              onMouseEnter={() => setActive(i)}
            >
              <span>{ci.name}</span>
              <span className="muted">{ci.class.name}</span>
              {ci.hostname && <span className="muted mono">{ci.hostname}</span>}
            </li>
          ))}
          {data && data.page.total > items.length && (
            <li className="note">
              {data.page.total - items.length} more — keep typing to narrow down
            </li>
          )}
        </ul>
      )}
    </div>
  );
}

// frontend/src/components/CiPicker.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, useId } from "vue";
import { useCiList, type CiSummary } from "../api/queries";
import { useDebounced } from "../lib/composables";

/**
 * Type-ahead picker for a configuration item. Queries the API server-side
 * (optionally restricted to a class and its subclasses); never loads the inventory.
 */
const props = withDefaults(
  defineProps<{
    id?: string;
    classId?: string | null;
    excludeId?: string;
    selected: { id: string; name: string } | null;
    placeholder?: string;
    invalid?: boolean;
    describedBy?: string;
  }>(),
  { id: undefined, classId: undefined, excludeId: undefined, placeholder: "Search by name, hostname, IP…", describedBy: undefined },
);
const emit = defineEmits<{ select: [ci: CiSummary | null] }>();

const autoId = useId();
const inputId = computed(() => props.id ?? autoId);
const listId = computed(() => `${inputId.value}-list`);
const text = ref("");
const open = ref(false);
const active = ref(0);
const q = useDebounced(() => text.value.trim(), 200);
const { data, isFetching, isError } = useCiList(() => ({
  q: q.value || undefined,
  classId: props.classId || undefined,
  limit: 15,
  sort: "name",
}));
const items = computed(() => (data.value?.data ?? []).filter((c) => c.id !== props.excludeId));

function choose(ci: CiSummary) {
  emit("select", ci);
  text.value = "";
  open.value = false;
}

function onInput(e: Event) {
  clearTimeout(closeTimer);
  text.value = (e.target as HTMLInputElement).value;
  open.value = true;
  active.value = 0;
}

function onKeydown(e: KeyboardEvent) {
  if (e.key === "ArrowDown") {
    e.preventDefault();
    open.value = true;
    active.value = Math.min(active.value + 1, items.value.length - 1);
  } else if (e.key === "ArrowUp") {
    e.preventDefault();
    active.value = Math.max(active.value - 1, 0);
  } else if (e.key === "Enter" && open.value && items.value[active.value]) {
    e.preventDefault();
    choose(items.value[active.value]);
  } else if (e.key === "Escape") {
    open.value = false;
  }
}

// Close shortly after blur so a click on an option still lands. A later focus or
// keystroke cancels the pending close, or a stale timer would shut the next list.
let closeTimer: ReturnType<typeof setTimeout> | undefined;
function onBlur() {
  closeTimer = setTimeout(() => (open.value = false), 150);
}
function onFocus() {
  clearTimeout(closeTimer);
  open.value = true;
}
onBeforeUnmount(() => clearTimeout(closeTimer));
</script>

<template>
  <div v-if="selected" class="checkbox-row">
    <strong>{{ selected.name }}</strong>
    <button type="button" class="btn btn-sm" :aria-label="`Clear ${selected.name}`" @click="emit('select', null)">Change</button>
  </div>
  <div v-else class="combo">
    <input
      :id="inputId"
      type="search"
      role="combobox"
      :aria-expanded="open"
      :aria-controls="listId"
      aria-autocomplete="list"
      :aria-activedescendant="open && items[active] ? `${listId}-${active}` : undefined"
      :aria-invalid="invalid || undefined"
      :aria-describedby="describedBy"
      autocomplete="off"
      :placeholder="placeholder"
      :value="text"
      style="width: 280px"
      @input="onInput"
      @focus="onFocus"
      @blur="onBlur"
      @keydown="onKeydown"
    />
    <ul v-if="open" :id="listId" class="combo-list" role="listbox">
      <li v-if="isError" class="note">Search failed</li>
      <li v-else-if="items.length === 0" class="note">{{ isFetching ? "Searching…" : "No matching CIs" }}</li>
      <li
        v-for="(ci, i) in items"
        :id="`${listId}-${i}`"
        :key="ci.id"
        role="option"
        :aria-selected="i === active"
        @mousedown.prevent="choose(ci)"
        @mouseenter="active = i"
      >
        <span>{{ ci.name }}</span>
        <span class="muted">{{ ci.class.name }}</span>
        <span v-if="ci.hostname" class="muted mono">{{ ci.hostname }}</span>
      </li>
      <li v-if="data && data.page.total > items.length" class="note">
        {{ data.page.total - items.length }} more — keep typing to narrow down
      </li>
    </ul>
  </div>
</template>
