// frontend/src/components/LookupSelect.tsx
import { useLookup, type LookupKind } from "../api/queries";

/** <select> over a lookup list (status, environment, owner, location). Retired rows are hidden unless selected. */
export function LookupSelect({
  kind,
  id,
  value,
  onChange,
  emptyLabel,
  invalid,
  describedBy,
  required,
}: {
  kind: LookupKind;
  id: string;
  value: string;
  onChange: (value: string) => void;
  emptyLabel: string;
  invalid?: boolean;
  describedBy?: string;
  required?: boolean;
}) {
  const { data, isLoading, isError } = useLookup(kind);
  const options = (data ?? []).filter((o) => o.isActive || o.id === value);
  return (
    <select
      id={id}
      value={value}
      onChange={(e) => onChange(e.target.value)}
      aria-invalid={invalid || undefined}
      aria-describedby={describedBy}
      required={required}
      disabled={isLoading}
    >
      <option value="">{isLoading ? "Loading…" : isError ? "Could not load options" : emptyLabel}</option>
      {options.map((o) => (
        <option key={o.id} value={o.id}>
          {"  ".repeat(o.depth ?? 0)}
          {o.name}
          {o.isActive ? "" : " (retired)"}
        </option>
      ))}
    </select>
  );
}

// frontend/src/components/LookupSelect.vue
<script setup lang="ts">
import { computed } from "vue";
import { useLookup, type LookupKind } from "../api/queries";

/** <select> over a lookup list (status, environment, owner, location). Retired rows are hidden unless selected. */
const props = defineProps<{
  kind: LookupKind;
  id: string;
  emptyLabel: string;
  invalid?: boolean;
  describedBy?: string;
  required?: boolean;
}>();
const model = defineModel<string>({ required: true });
const { data, isLoading, isError } = useLookup(props.kind);
const options = computed(() => (data.value ?? []).filter((o) => o.isActive || o.id === model.value));
</script>

<template>
  <select
    :id="id"
    v-model="model"
    :aria-invalid="invalid || undefined"
    :aria-describedby="describedBy"
    :required="required"
    :disabled="isLoading"
  >
    <option value="">{{ isLoading ? "Loading…" : isError ? "Could not load options" : emptyLabel }}</option>
    <option v-for="o in options" :key="o.id" :value="o.id">
      {{ "\u00a0\u00a0".repeat(o.depth ?? 0) }}{{ o.name }}{{ o.isActive ? "" : " (retired)" }}
    </option>
  </select>
</template>
